# Generated by Django 6.0.3 on 2026-03-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_venuefeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuefeed',
            name='default_genre',
            field=models.ForeignKey(blank=True, help_text='Applied to imported events when category is Music', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.genre'),
        ),
        migrations.AlterField(
            model_name='calendarfeed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('music', 'Music'), ('arts', 'Arts & Comedy'), ('bike', 'Bike'), ('fund', 'Fundraiser'), ('food', 'Food'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venuefeed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venuefeed',
            name='source_type',
            field=models.CharField(choices=[('ical', 'iCal Feed'), ('eventbrite', 'Eventbrite API'), ('musicbrainz', 'MusicBrainz API')], default='ical', max_length=20),
        ),
    ]
