# Generated by Django 6.0.3 on 2026-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_venuefeed_default_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mb_id', models.CharField(blank=True, help_text='MusicBrainz artist ID', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, help_text='Performing artists / headliners', related_name='events', to='events.artist'),
        ),
        migrations.AddField(
            model_name='venuefeed',
            name='residents',
            field=models.ManyToManyField(blank=True, help_text='Regular/resident artists — auto-tagged on every imported event', related_name='resident_feeds', to='events.artist'),
        ),
    ]
