# Generated by Django 6.0.3 on 2026-03-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_artist_residents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuefeed',
            name='default_genre',
        ),
        migrations.AddField(
            model_name='venuefeed',
            name='default_genres',
            field=models.ManyToManyField(blank=True, help_text='Applied to imported events when category is Music', related_name='venue_feeds', to='events.genre'),
        ),
    ]
