# Generated by Django 6.0.3 on 2026-03-30 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_default_genres_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, choices=[('music', 'Music'), ('arts', 'Arts & Comedy'), ('bike', 'Bike'), ('fund', 'Fundraiser'), ('food', 'Food'), ('hybrid', 'Hybrid')], max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('price_info', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recurring/')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly_date', 'Monthly (same date each month)'), ('monthly_weekday', 'Monthly (e.g. every 3rd Thursday)'), ('annually', 'Annually')], max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Every N units — e.g. 2 = bi-weekly')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], help_text='For weekly / monthly-weekday frequency', null=True)),
                ('week_of_month', models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, 'Last')], help_text='1-5 for monthly-weekday (5 = last)', null=True)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120, help_text='Duration in minutes (0 = no end time)')),
                ('active', models.BooleanField(default=True)),
                ('auto_approve', models.BooleanField(default=False)),
                ('lookahead_weeks', models.PositiveIntegerField(default=12, help_text='Generate instances this many weeks ahead')),
                ('submitted_by', models.CharField(blank=True, max_length=100)),
                ('submitted_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='recurring_events', to='events.genre')),
                ('residents', models.ManyToManyField(blank=True, related_name='recurring_events', to='events.artist')),
                ('submitted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='events.recurringevent'),
        ),
    ]
