# Generated by Django 6.0.3 on 2026-04-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_recurring_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cron Status',
                'verbose_name_plural': 'Cron Status',
                'managed': False,
            },
        ),
    ]
