# Generated by Django 6.0.3 on 2026-04-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_cronstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuefeed',
            name='source_type',
            field=models.CharField(choices=[('ical', 'iCal Feed'), ('eventbrite', 'Eventbrite API'), ('musicbrainz', 'MusicBrainz API'), ('squarespace', 'Squarespace Events JSON')], default='ical', max_length=20),
        ),
    ]
