# Generated by Django 6.0.3 on 2026-04-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_venuefeed_squarespace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(help_text='Physical address — used to match events automatically', max_length=300)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('instagram', models.CharField(blank=True, help_text='Handle without @', max_length=100)),
                ('bandcamp', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False, help_text='Admin-verified venue')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_venues', to=settings.AUTH_USER_MODEL)),
                ('venue_feed', models.OneToOneField(blank=True, help_text='Link to the iCal feed we import events from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_profile', to='events.venuefeed')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
