# Generated by Django 6.0.3 on 2026-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_venue_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='discord',
            field=models.URLField(blank=True, help_text='Invite link'),
        ),
        migrations.AddField(
            model_name='venue',
            name='mastodon',
            field=models.URLField(blank=True, help_text='Full profile URL e.g. https://pdx.social/@yourhandle'),
        ),
        migrations.AddField(
            model_name='venue',
            name='medium',
            field=models.CharField(blank=True, help_text='Username without @', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='twitter',
            field=models.CharField(blank=True, help_text='Handle without @', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
