# Generated by Django 6.0.3 on 2026-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_venue_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='bluesky',
            field=models.CharField(blank=True, help_text='Handle without @ e.g. yourname.bsky.social', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Company page slug', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='mixcloud',
            field=models.CharField(blank=True, help_text='Username / profile slug', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='soundcloud',
            field=models.CharField(blank=True, help_text='Username / profile slug', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='threads',
            field=models.CharField(blank=True, help_text='Handle without @', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='tiktok',
            field=models.CharField(blank=True, help_text='Handle without @', max_length=100),
        ),
    ]
