# Generated by Django 6.0.3 on 2026-04-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_venue_socials_extended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short history / character blurb — shown on neighborhood page. Sourced from Wikipedia or written by hand.')),
                ('wiki_url', models.URLField(blank=True, help_text='Wikipedia article URL for attribution')),
                ('latitude', models.FloatField(blank=True, help_text='Center-point for distance queries', null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venuefeed',
            name='source_type',
            field=models.CharField(choices=[('ical', 'iCal Feed'), ('eventbrite', 'Eventbrite API'), ('musicbrainz', 'MusicBrainz API'), ('squarespace', 'Squarespace Events JSON'), ('19hz', '19hz.info PNW Listing')], default='ical', max_length=20),
        ),
    ]
