# Generated by Django 6.0.3 on 2026-04-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_view_counts_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='aliases',
            field=models.TextField(blank=True, help_text='Pipe-separated list of alternative names used in event.neighborhood (e.g. "Eliot|Boise"). Used when the display name differs from how events are tagged.'),
        ),
    ]
