# Generated by Django 6.0.3 on 2026-04-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_neighborhood_aliases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='Public @handle — lowercase letters, numbers, underscores only.', max_length=50, unique=True)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('links', models.JSONField(blank=True, default=list, help_text='List of {"label": "...", "url": "..."} dicts.')),
                ('is_public', models.BooleanField(default=True, help_text='Show public profile page')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email_verified', models.BooleanField(default=False)),
                ('verify_token', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
