# Generated by Django 6.0.3 on 2026-04-07 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('event', 'Event'), ('venue', 'Venue'), ('artist', 'Artist'), ('neighborhood', 'Neighborhood')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=50)),
                ('current_value', models.TextField(blank=True)),
                ('suggested_value', models.TextField()),
                ('note', models.TextField(blank=True, help_text='Why this edit is needed (optional)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edit Suggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
