# Generated by Django 6.0.3 on 2026-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_editsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='closed_date',
            field=models.DateField(blank=True, help_text='Date venue closed (for display)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='venue',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to mark venue as permanently closed'),
        ),
    ]
