# Generated by Django 6.0.3 on 2026-04-14 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_venue_closed_date_event_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bandcamp',
            field=models.URLField(blank=True, help_text='Full Bandcamp URL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='bluesky',
            field=models.CharField(blank=True, help_text='Handle e.g. yourname.bsky.social', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='drive_folder_url',
            field=models.URLField(blank=True, help_text='Public Google Drive folder URL — live sets, DJ sessions, mixes'),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, help_text='Handle without @', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin-verified artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='mastodon',
            field=models.URLField(blank=True, help_text='Full profile URL e.g. https://pdx.social/@you'),
        ),
        migrations.AddField(
            model_name='artist',
            name='mixcloud',
            field=models.CharField(blank=True, help_text='Username / profile slug', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud',
            field=models.CharField(blank=True, help_text='Username / profile slug', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify',
            field=models.URLField(blank=True, help_text='Artist page URL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='tiktok',
            field=models.CharField(blank=True, help_text='Handle without @', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='PromoterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='promoters/')),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, help_text='Handle without @', max_length=100)),
                ('soundcloud', models.CharField(blank=True, help_text='Username / profile slug', max_length=100)),
                ('bandcamp', models.URLField(blank=True)),
                ('mixcloud', models.CharField(blank=True, help_text='Username / profile slug', max_length=100)),
                ('youtube', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('mastodon', models.URLField(blank=True, help_text='Full profile URL')),
                ('bluesky', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('discord', models.URLField(blank=True, help_text='Invite link')),
                ('drive_folder_url', models.URLField(blank=True, help_text='Public Google Drive folder URL — live sets, DJ sessions, mixes')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_promoters', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='promoters', to='events.genre')),
            ],
            options={
                'verbose_name': 'Promoter / Crew',
                'verbose_name_plural': 'Promoters / Crews',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('artist_name', models.CharField(blank=True, help_text='Parsed from filename or metadata', max_length=200)),
                ('genre_raw', models.CharField(blank=True, help_text='Raw genre string from filename', max_length=100)),
                ('recorded_at', models.CharField(blank=True, help_text='Venue or event name', max_length=200)),
                ('recorded_date', models.DateField(blank=True, null=True)),
                ('duration_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True, help_text='Cached direct stream URL', max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('position', models.PositiveIntegerField(default=0, help_text='Sort order within folder')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='events.genre')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.venue')),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.promoterprofile')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
    ]
