# Generated by Django 6.0.3 on 2026-04-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_backfill_artist_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='target_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('venue', 'Venue'), ('neighborhood', 'Neighborhood'), ('promoter', 'Promoter')], max_length=20),
        ),
    ]
