# Generated by Django 6.0.3 on 2026-04-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_follow_add_promoter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
