# Generated by Django 6.0.3 on 2026-04-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_savedtrack_and_track_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='promoters',
            field=models.ManyToManyField(blank=True, help_text='Crews / promoters for this event', related_name='events', to='events.promoterprofile'),
        ),
    ]
