# Generated by Django 6.0.3 on 2026-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_event_promoters_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterprofile',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Artists / DJs who are members of this crew', related_name='crews', to='events.artist'),
        ),
    ]
