# Generated by Django 6.0.3 on 2026-04-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_promoter_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterprofile',
            name='shop_sheet_url',
            field=models.URLField(blank=True, help_text='Public Google Sheets URL — your record inventory (Artist, Title, Label, Year, Format, Condition, Price SOL, Notes)'),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='sol_wallet',
            field=models.CharField(blank=True, help_text='Solana wallet address — payments go here (e.g. Phantom public key)', max_length=120),
        ),
        migrations.CreateModel(
            name='RecordListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(default=0, help_text='Row position in sheet (for ordering/dedup)')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('format', models.CharField(blank=True, help_text='e.g. Vinyl, LP, 12", CD', max_length=50)),
                ('condition', models.CharField(blank=True, choices=[('M', 'Mint (M)'), ('NM', 'Near Mint (NM)'), ('VG+', 'Very Good Plus (VG+)'), ('VG', 'Very Good (VG)'), ('G+', 'Good Plus (G+)'), ('G', 'Good (G)'), ('F', 'Fair (F)'), ('P', 'Poor (P)')], max_length=4)),
                ('price_sol', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, help_text='Pulled from Discogs')),
                ('discogs_id', models.CharField(blank=True, max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_listings', to='events.promoterprofile')),
            ],
            options={
                'ordering': ['row_index'],
            },
        ),
    ]
