# Generated by Django 6.0.3 on 2026-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_promoter_shop_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterprofile',
            name='shop_open_to_trade',
            field=models.BooleanField(default=False, help_text='Open to record trades / partial trades'),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='shop_pay_in_person',
            field=models.BooleanField(default=False, help_text='Accept in-person payment at events / pickup'),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Username without @', max_length=100),
        ),
    ]
