# Generated by Django 6.0.3 on 2026-04-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_promoter_telegram_shop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlisting',
            name='price_display',
            field=models.CharField(blank=True, help_text='Raw price from sheet e.g. "$ 30" or "0.5 SOL"', max_length=50),
        ),
    ]
