# Generated by Django 6.0.3 on 2026-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_record_price_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlisting',
            name='genres',
            field=models.CharField(blank=True, help_text='Discogs genres, comma-separated', max_length=200),
        ),
        migrations.AddField(
            model_name='recordlisting',
            name='styles',
            field=models.CharField(blank=True, help_text='Discogs styles, comma-separated', max_length=200),
        ),
    ]
