# Generated by Django 6.0.3 on 2026-04-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_record_genres_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=120)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_contact', models.CharField(blank=True, help_text='Discord handle, Telegram, phone, etc.', max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.recordlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
