# Generated by Django 6.0.3 on 2026-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_reservation_buyer_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterprofile',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Internal contact email — used to send claim instructions. Not shown publicly.', max_length=254),
        ),
    ]
