# Generated by Django 6.0.3 on 2026-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_promoter_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlisting',
            name='preview_url',
            field=models.URLField(blank=True, help_text='YouTube video URL from Discogs — for in-card preview player'),
        ),
    ]
