# Generated by Django 6.0.3 on 2026-04-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_record_listing_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuefeed',
            name='promoter',
            field=models.ForeignKey(blank=True, help_text='Promoter/crew this feed belongs to — events are auto-linked to their profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='events.promoterprofile'),
        ),
    ]
