# Generated by Django 6.0.3 on 2026-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_venuefeed_promoter_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestats',
            name='daily_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestats',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
