# Generated by Django 6.0.3 on 2026-04-16 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_sitestats_daily_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=20, unique=True)),
                ('youtube_channel_id', models.CharField(db_index=True, max_length=40)),
                ('channel_title', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('artist_name_display', models.CharField(blank=True, help_text='Denormalized display name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from MTV channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='events.artist')),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='events.promoterprofile')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='events.venue')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
