# Generated by Django 6.0.3 on 2026-04-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_videotrack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotrack',
            options={'ordering': ['-is_live', '-published_at']},
        ),
        migrations.AddField(
            model_name='artist',
            name='twitch',
            field=models.CharField(blank=True, help_text='Channel name without @', max_length=100),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='twitch',
            field=models.CharField(blank=True, help_text='Channel name without @', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='twitch',
            field=models.CharField(blank=True, help_text='Channel name without @', max_length=100),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='is_live',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='live_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='live_viewer_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('twitch_vod', 'Twitch VOD'), ('twitch_live', 'Twitch Live')], db_index=True, default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='twitch_username',
            field=models.CharField(blank=True, help_text='Twitch channel name (for live streams and VODs)', max_length=100),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='twitch_video_id',
            field=models.CharField(blank=True, help_text='Twitch VOD ID (numeric)', max_length=30),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='youtube_channel_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='youtube_video_id',
            field=models.CharField(help_text='YouTube video ID, or synthetic twitch_live_{user} / twitch_vod_{id}', max_length=60, unique=True),
        ),
    ]
