# Generated by Django 6.0.3 on 2026-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_userprofile_messengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='messenger_discord',
            field=models.CharField(blank=True, help_text='Discord user ID (numeric) — links to discord.com/users/ID. Find it: Settings → Advanced → Developer Mode, then right-click your name.', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='messenger_signal',
            field=models.CharField(blank=True, help_text='Signal username (without +) — links to signal.me', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='messenger_telegram',
            field=models.CharField(blank=True, help_text='Telegram handle without @ — links to t.me/handle', max_length=100),
        ),
    ]
