# Generated by Django 6.0.3 on 2026-04-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_shelter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('shelter_type', models.CharField(choices=[('emergency', 'Emergency Shelter'), ('warming', 'Warming Center'), ('cooling', 'Cooling Center'), ('overnight', 'Overnight Shelter'), ('day', 'Day Shelter / Drop-in'), ('hygiene', 'Hygiene Services'), ('tiny_home', 'Tiny Home Village'), ('transitional', 'Transitional Housing'), ('youth', 'Youth Shelter'), ('family', 'Family Shelter'), ('womens', "Women's Shelter"), ('veteran', 'Veterans Services'), ('sobering', 'Sobering / Detox Center'), ('hotline', 'Hotline / Phone Resource')], default='emergency', max_length=20)),
                ('accepts', models.CharField(choices=[('all', 'Everyone'), ('women', 'Women / Non-binary'), ('men', 'Men'), ('youth', 'Youth (under 25)'), ('families', 'Families with children'), ('lgbtq', 'LGBTQ+ affirming'), ('veteran', 'Veterans')], default='all', help_text='Primary population served', max_length=20)),
                ('pets_ok', models.BooleanField(default=False, help_text='Pets accepted')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('hours', models.CharField(blank=True, help_text='e.g. "Mon–Fri 7am–9pm" or "24/7"', max_length=300)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Bed/mat capacity if known', null=True)),
                ('notes', models.TextField(blank=True, help_text='Intake requirements, IDs needed, languages, etc.')),
                ('available_hot', models.BooleanField(default=False, help_text='Cooling center — promote on hot-weather days (>90°F)')),
                ('available_cold', models.BooleanField(default=True, help_text='Warming center — promote on cold days (<35°F)')),
                ('available_smoke', models.BooleanField(default=False, help_text='Indoor/filtered air — promote on high-particulate days')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shelter / Resource',
                'verbose_name_plural': 'Shelters & Resources',
                'ordering': ['shelter_type', 'name'],
            },
        ),
    ]
