# Generated by Django 6.0.3 on 2026-04-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_shelter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestats',
            name='tracking_started',
            field=models.DateField(blank=True, help_text='Date counting began — used to compute all-time avg daily', null=True),
        ),
    ]
