# Generated by Django 6.0.3 on 2026-04-20 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_artist_discogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='Handle without @, e.g. rave.pdx', max_length=100, unique=True)),
                ('ig_user_id', models.CharField(blank=True, max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('follower_count', models.IntegerField(blank=True, null=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this account')),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
                'ordering': ['handle'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_post_id', models.CharField(max_length=100, unique=True)),
                ('shortcode', models.CharField(max_length=100, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('is_video', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='events.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'ordering': ['-posted_at'],
            },
        ),
    ]
