# Generated by Django 6.0.3 on 2026-04-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_instagram_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('active', 'Active — harvest posts'), ('rejected', 'Rejected — skip')], default='active', help_text='Active accounts are harvested; pending awaits review', max_length=20),
        ),
    ]
