# Generated by Django 6.0.3 on 2026-04-20 04:44

from django.db import migrations, models


def strings_to_lists(apps, schema_editor):
    PromoterProfile = apps.get_model('events', 'PromoterProfile')
    for p in PromoterProfile.objects.all():
        if isinstance(p.promoter_type, str):
            p.promoter_type = [p.promoter_type] if p.promoter_type else ['crew']
            p.save(update_fields=['promoter_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_instagram_status'),
    ]

    operations = [
        # Convert existing string values to JSON arrays BEFORE AlterField adds JSON_VALID constraint
        migrations.RunSQL(
            "UPDATE events_promoterprofile SET promoter_type = json_array(promoter_type) "
            "WHERE promoter_type IS NOT NULL AND promoter_type NOT LIKE '[%'",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='promoterprofile',
            name='promoter_type',
            field=models.JSONField(default=list, help_text='One or more types — stored as a JSON list, e.g. ["crew", "record_swap"]'),
        ),
    ]
