# Generated by Django 6.0.3 on 2026-04-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_tracking_started'),
        ('events', '0058_promoter_type_multi'),
    ]

    operations = [
    ]
