# Generated by Django 6.0.3 on 2026-04-20 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_merge_0052_tracking_started_0058_promoter_type_multi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='flyer_backgrounds/%Y/')),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flyer_backgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flyer Background',
                'verbose_name_plural': 'Flyer Backgrounds',
                'ordering': ['created_at'],
            },
        ),
    ]
