# Generated by Django 6.0.3 on 2026-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_flyer_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_following',
            field=models.BooleanField(default=False, help_text='Show following list on public profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_saved_tracks',
            field=models.BooleanField(default=False, help_text='Show saved tracks on public profile'),
        ),
    ]
