# Generated by Django 6.0.3 on 2026-04-21 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_flyer_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterprofile',
            name='accept_demos',
            field=models.BooleanField(default=False, help_text='Allow logged-in users to upload MP3 demos/mixes directly to this profile'),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='demo_folder_url',
            field=models.URLField(blank=True, help_text='Optional: Google Drive folder for submitted demos (requires service account). If blank, files are stored locally.'),
        ),
        migrations.CreateModel(
            name='TrackShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('audio_file', models.FileField(upload_to='demos/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_tracks', to='events.promoterprofile')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
