# Generated by Django 6.0.3 on 2026-04-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_userprofile_privacy_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_embeds',
            field=models.BooleanField(default=True, help_text='Show music embeds on public profile'),
        ),
    ]
