# Generated by Django 6.0.3 on 2026-04-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_userprofile_show_embeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_rss_feed',
            field=models.BooleanField(default=False, help_text='Show RSS feed link on public profile'),
        ),
    ]
