# Generated by Django 6.0.3 on 2026-04-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_userprofile_show_rss'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastfm_username',
            field=models.CharField(blank=True, help_text='Last.fm username', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='listenbrainz_username',
            field=models.CharField(blank=True, help_text='ListenBrainz username', max_length=100),
        ),
    ]
