# Generated by Django 6.0.3 on 2026-04-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_trackshare_accept_demos'),
        ('events', '0067_userplaylist'),
    ]

    operations = [
    ]
