# Generated by Django 6.0.3 on 2026-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_merge_0061_trackshare_accept_demos_0067_userplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoterprofile',
            name='accept_demos',
        ),
        migrations.RemoveField(
            model_name='promoterprofile',
            name='demo_folder_url',
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='TrackShare',
        ),
    ]
