# Generated by Django 6.0.3 on 2026-04-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_merge_0061_trackshare_accept_demos_0067_userplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('geocode_event', 'Geocode Event'), ('geocode_venue', 'Geocode Venue'), ('post_bluesky', 'Post to Bluesky')], db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='queued', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'task_type'], name='events_work_status_7ad622_idx')],
            },
        ),
    ]
