# Generated by Django 6.0.3 on 2026-04-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_remove_promoterprofile_accept_demos_and_more'),
        ('events', '0069_worker_task'),
    ]

    operations = [
    ]
