# Generated by Django 6.0.3 on 2026-04-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_merge_20260423_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Internal contact email — used to send claim instructions. Not shown publicly.', max_length=254),
        ),
        migrations.AlterField(
            model_name='venuefeed',
            name='source_type',
            field=models.CharField(choices=[('ical', 'iCal Feed'), ('eventbrite', 'Eventbrite API'), ('musicbrainz', 'MusicBrainz API'), ('squarespace', 'Squarespace Events JSON'), ('19hz', '19hz.info PNW Listing'), ('eael', 'EAEL WordPress Calendar (data-events scrape)')], default='ical', max_length=20),
        ),
    ]
