# Generated by Django 6.0.3 on 2026-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_artist_house_mixes_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='twitch_unresolvable',
            field=models.BooleanField(default=False, help_text='Twitch username returned 400 — needs review'),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='twitch_unresolvable',
            field=models.BooleanField(default=False, help_text='Twitch username returned 400 — needs review'),
        ),
    ]
