# Generated by Django 6.0.3 on 2026-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_twitch_unresolvable_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='link_broken',
            field=models.BooleanField(default=False, help_text='Website URL returned 4xx/5xx (check_links cron)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='link_checked_at',
            field=models.DateTimeField(blank=True, help_text='Last time website URL was checked', null=True),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='link_broken',
            field=models.BooleanField(default=False, help_text='Website URL returned 4xx/5xx (check_links cron)'),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='link_checked_at',
            field=models.DateTimeField(blank=True, help_text='Last time website URL was checked', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='link_broken',
            field=models.BooleanField(default=False, help_text='Website URL returned 4xx/5xx (check_links cron)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='link_checked_at',
            field=models.DateTimeField(blank=True, help_text='Last time website URL was checked', null=True),
        ),
    ]
