# Generated by Django 6.0.3 on 2026-04-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0082_communityspace'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videoroommessage',
            new_name='events_vide_created_da7f2e_idx',
            old_name='events_vide_created_14a91f_idx',
        ),
        migrations.AlterField(
            model_name='communityspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
