# Generated by Django 6.0.3 on 2026-04-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0087_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communityask',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='Product thumbnail URL (auto-fetchable from page)'),
        ),
    ]
