# Generated by Django 6.0.3 on 2026-04-30 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0094_trackcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Primary genre — used for video track filtering when no PlaylistTrack genre exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='events.genre'),
        ),
        migrations.AlterField(
            model_name='communityspace',
            name='kofi',
            field=models.CharField(blank=True, help_text='Ko-fi page ID or username e.g. U7U813CDB7 from ko-fi.com/U7U813CDB7 — embeds posts feed on profile', max_length=100),
        ),
        migrations.AlterField(
            model_name='communityspace',
            name='kofi_token',
            field=models.CharField(blank=True, help_text='Auto-generated webhook verification token — paste this into Ko-fi Settings → Webhooks', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kofipost',
            name='kofi_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Subscription', 'Subscription'), ('Shop_Order', 'Shop Order'), ('Commission', 'Commission'), ('Blog_Post', 'Blog Post')], default='Donation', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes — not visible to submitter'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackreaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
