# Generated by Django 6.0.3 on 2026-04-30 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_artist_genre_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, max_length=200)),
                ('track_title', models.CharField(blank=True, max_length=300)),
                ('current_genre', models.CharField(blank=True, help_text='Genre on the track at time of suggestion', max_length=100)),
                ('suggested_genre', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_suggestions', to='events.playlisttrack')),
                ('video_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_suggestions', to='events.videotrack')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='events_genr_status_6fa4e6_idx')],
            },
        ),
    ]
