# Generated by Django 6.0.3 on 2026-04-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_genre_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='lastfm_listeners',
            field=models.PositiveIntegerField(blank=True, help_text='Last.fm monthly listener count', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='lastfm_similar',
            field=models.JSONField(blank=True, default=list, help_text='Similar artist names from Last.fm — list of strings'),
        ),
    ]
