# Generated by Django 6.0.3 on 2026-04-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0097_artist_lastfm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='enrichment_locked',
            field=models.BooleanField(default=False, help_text='Skip all automated enrichment for this artist — set when API data does not match'),
        ),
    ]
