services:
  cp-local:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./templates:/app/templates
      - ./static:/app/static
      - ./events/migrations:/app/events/migrations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cp-local.rule=Host(`local.communityplaylist.com`)"
      - "traefik.http.routers.cp-local.entrypoints=websecure"
      - "traefik.http.routers.cp-local.tls=true"
      - "traefik.http.services.cp-local.loadbalancer.server.port=8000"
    networks:
      - traefik

networks:
  traefik:
    external: true
