f = open('/var/www/vhosts/communityplaylist.com/django/templates/events/event_list.html', 'w')
f.write('\n')
f.write('\n')
f.write('\n')
f.write('\n')
f.write('Community Playlist - PDX Events\n')
f.write('\n')
f.write('*{margin:0;padding:0;box-sizing:border-box}\n')
f.write('body{background:#111;color:#eee;font-family:sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;text-align:center;padding:20px}\n')
f.write('.wrap{max-width:600px}\n')
f.write('img{max-width:320px;width:100%;margin-bottom:32px}\n')
f.write('h1{font-size:2em;color:#ff6b35;margin-bottom:12px;letter-spacing:.05em}\n')
f.write('p{color:#aaa;font-size:1.1em;line-height:1.6;margin-bottom:8px}\n')
f.write('.pdx{color:#ff6b35;font-weight:bold}\n')
f.write('\n')
f.write('\n')
f.write('\n')
f.write('Coming Soon\n')
f.write('Portland community events — submitted by the people, for the people.\n')
f.write('Built with love for PDX 🌹\n')
f.write('\n')
f.close()
print('Done')
