from django.core.management.base import BaseCommand
from events.models import Shelter


SHELTERS = [
    # --- Emergency ---
    {
        'name': 'JOIN PDX - Street Outreach',
        'shelter_type': 'emergency',
        'accepts': 'all',
        'address': '4126 NE Sandy Blvd, Portland, OR 97212',
        'neighborhood': 'Hollywood',
        'latitude': 45.5311,
        'longitude': -122.6277,
        'phone': '503-232-0007',
        'website': 'https://joinpdx.org',
        'hours': 'Mon–Fri 9am–5pm (outreach 24/7)',
        'notes': 'Street outreach, shelter navigation, transitional housing referrals.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    {
        'name': 'Salvation Army Harbor Light Center',
        'shelter_type': 'emergency',
        'accepts': 'men',
        'address': '333 NW 6th Ave, Portland, OR 97209',
        'neighborhood': 'Old Town',
        'latitude': 45.5249,
        'longitude': -122.6762,
        'phone': '503-226-3213',
        'website': 'https://www.salvationarmyusawest.org/portland',
        'hours': '24/7',
        'notes': 'Emergency shelter for men. Meals, case management, recovery services.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': True,
        'pets_ok': False,
    },
    {
        'name': 'Central City Concern - Old Town Recovery Center',
        'shelter_type': 'emergency',
        'accepts': 'all',
        'address': '40 NW 3rd Ave, Portland, OR 97209',
        'neighborhood': 'Old Town',
        'latitude': 45.5231,
        'longitude': -122.6732,
        'phone': '503-294-1681',
        'website': 'https://centralcityconcern.org',
        'hours': '24/7',
        'notes': 'Emergency shelter, addiction recovery, primary care, housing services.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': True,
        'pets_ok': False,
    },
    {
        'name': 'Transition Projects - Jean\'s Place',
        'shelter_type': 'emergency',
        'accepts': 'women',
        'address': '211 NW Davis St, Portland, OR 97209',
        'neighborhood': 'Old Town',
        'latitude': 45.5235,
        'longitude': -122.6745,
        'phone': '503-280-4712',
        'website': 'https://www.tprojects.org',
        'hours': '24/7',
        'notes': 'Day shelter, showers, laundry, meals. No intake barriers.',
        'available_cold': True,
        'available_hot': True,
        'available_smoke': True,
        'pets_ok': False,
    },
    # --- Day Shelter / Drop-in ---
    {
        'name': 'Blanchet House',
        'shelter_type': 'day',
        'accepts': 'all',
        'address': '310 NW Glisan St, Portland, OR 97209',
        'neighborhood': 'Old Town',
        'latitude': 45.5248,
        'longitude': -122.6764,
        'phone': '503-241-4340',
        'website': 'https://blanchethouse.org',
        'hours': 'Daily — breakfast 7am, lunch 11:30am, dinner 5pm',
        'notes': 'Free meals, clothing, hygiene supplies. No intake required.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    {
        'name': 'Transition Projects - Clark Center',
        'shelter_type': 'day',
        'accepts': 'men',
        'address': '518 NW 6th Ave, Portland, OR 97209',
        'neighborhood': 'Old Town',
        'latitude': 45.5258,
        'longitude': -122.6762,
        'phone': '503-280-4712',
        'website': 'https://www.tprojects.org',
        'hours': 'Daily 7am–9pm',
        'notes': 'Day drop-in for men. Showers, laundry, case management.',
        'available_cold': True,
        'available_hot': True,
        'available_smoke': True,
        'pets_ok': False,
    },
    # --- Women's ---
    {
        'name': 'Rose Haven',
        'shelter_type': 'womens',
        'accepts': 'women',
        'address': '627 NW 18th Ave, Portland, OR 97209',
        'neighborhood': 'Northwest Portland',
        'latitude': 45.5261,
        'longitude': -122.6912,
        'phone': '503-248-6035',
        'website': 'https://rosehaven.org',
        'hours': 'Mon–Fri 9am–4pm, Sat 9am–1pm',
        'notes': 'Day shelter for women, children, and non-binary people. Meals, showers, laundry, mail, case management. No intake barriers.',
        'available_cold': True,
        'available_hot': True,
        'available_smoke': True,
        'pets_ok': True,
    },
    {
        'name': 'Bradley Angle - Emergency Shelter (DV)',
        'shelter_type': 'womens',
        'accepts': 'women',
        'address': 'Confidential — call for location',
        'neighborhood': 'Portland',
        'phone': '503-281-2442',
        'website': 'https://bradleyangle.org',
        'hours': '24/7 hotline',
        'notes': 'Domestic violence emergency shelter for women and children. Location kept confidential. Call the 24-hr hotline.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    # --- Youth ---
    {
        'name': 'Outside In',
        'shelter_type': 'youth',
        'accepts': 'youth',
        'address': '1132 SW 13th Ave, Portland, OR 97205',
        'neighborhood': 'SW Portland',
        'latitude': 45.5166,
        'longitude': -122.6873,
        'phone': '503-223-4121',
        'website': 'https://outsidein.org',
        'hours': 'Mon–Fri 9am–5pm (shelter referrals available)',
        'notes': 'LGBTQ+ affirming. Youth under 25. Drop-in services, shelter navigation, health clinic, employment help.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    {
        'name': 'New Avenues for Youth',
        'shelter_type': 'youth',
        'accepts': 'youth',
        'address': '1220 SW Columbia St, Portland, OR 97201',
        'neighborhood': 'Downtown',
        'latitude': 45.5148,
        'longitude': -122.6836,
        'phone': '503-224-4339',
        'website': 'https://newavenues.org',
        'hours': 'Mon–Fri 8am–5pm',
        'notes': 'Youth under 24. Drop-in, shelter navigation, employment, education. LGBTQ+ welcoming.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    # --- Overnight ---
    {
        'name': 'Bud Clark Commons',
        'shelter_type': 'overnight',
        'accepts': 'all',
        'address': '655 NW Second Ave, Portland, OR 97209',
        'neighborhood': 'Old Town',
        'latitude': 45.5244,
        'longitude': -122.6716,
        'phone': '503-823-5090',
        'website': 'https://www.portlandoregon.gov/phb/budclarkcommons',
        'hours': '24/7',
        'notes': 'Overnight shelter and day services. Referral required through 211info.',
        'available_cold': True,
        'available_hot': True,
        'available_smoke': True,
        'pets_ok': False,
    },
    # --- Warming ---
    {
        'name': 'Multnomah County Warming Centers (seasonal)',
        'shelter_type': 'warming',
        'accepts': 'all',
        'address': 'Multiple locations — call 211',
        'neighborhood': 'Portland metro',
        'phone': '211',
        'website': 'https://www.multco.us/dchs/severe-weather-emergency-shelters',
        'hours': 'Activated during freeze alerts (below 25°F)',
        'notes': 'Emergency warming shelters opened by the county during hard freeze alerts. Locations vary. Call 211 for current sites.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    # --- Cooling ---
    {
        'name': 'Multnomah County Cooling Centers (seasonal)',
        'shelter_type': 'cooling',
        'accepts': 'all',
        'address': 'Multiple locations — call 211',
        'neighborhood': 'Portland metro',
        'phone': '211',
        'website': 'https://www.multco.us/dchs/cooling-centers',
        'hours': 'Activated during heat emergencies',
        'notes': 'Emergency cooling centers opened during extreme heat events. Locations vary. Call 211 for current sites.',
        'available_cold': False,
        'available_hot': True,
        'available_smoke': False,
        'pets_ok': True,
    },
    # --- Hygiene ---
    {
        'name': 'Portland Loo / Community Hygiene Hubs',
        'shelter_type': 'hygiene',
        'accepts': 'all',
        'address': 'Multiple locations citywide',
        'neighborhood': 'Portland metro',
        'phone': '503-823-4000',
        'website': 'https://www.portland.gov/omf/portland-loo',
        'hours': 'Varies by location',
        'notes': 'Public restrooms and hand washing. Some sites offer showers, laundry.',
        'available_cold': False,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    # --- Veteran ---
    {
        'name': 'Home Forward Veterans Services',
        'shelter_type': 'veteran',
        'accepts': 'veteran',
        'address': '135 SW Ash St, Portland, OR 97204',
        'neighborhood': 'Downtown',
        'latitude': 45.5228,
        'longitude': -122.6728,
        'phone': '503-802-8300',
        'website': 'https://homeforward.org',
        'hours': 'Mon–Fri 8am–5pm',
        'notes': 'Housing vouchers, rental assistance, and veteran-specific case management.',
        'available_cold': False,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    # --- Sobering ---
    {
        'name': 'Central City Concern - Hooper Detox',
        'shelter_type': 'sobering',
        'accepts': 'all',
        'address': '1615 SE Bybee Blvd, Portland, OR 97202',
        'neighborhood': 'Sellwood',
        'latitude': 45.4786,
        'longitude': -122.6460,
        'phone': '503-238-2067',
        'website': 'https://centralcityconcern.org/recovery/detox',
        'hours': '24/7',
        'notes': 'Medical detox and sobering. No intake barriers for sobering. Residential detox requires assessment.',
        'available_cold': True,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
    # --- Hotlines ---
    {
        'name': '211info — Oregon / SW Washington',
        'shelter_type': 'hotline',
        'accepts': 'all',
        'address': 'Phone / online',
        'phone': '211',
        'website': 'https://211info.org',
        'hours': '24/7',
        'notes': 'Free, confidential referrals to food, shelter, health, housing, and crisis services. Text your zip to 898-211.',
        'available_cold': True,
        'available_hot': True,
        'available_smoke': True,
        'pets_ok': False,
    },
    {
        'name': 'Lines for Life — Crisis Line',
        'shelter_type': 'hotline',
        'accepts': 'all',
        'address': 'Phone only',
        'phone': '503-215-7082',
        'website': 'https://www.linesforlife.org',
        'hours': '24/7',
        'notes': 'Mental health crisis support, suicide prevention, substance use counseling. Multilingual available.',
        'available_cold': False,
        'available_hot': False,
        'available_smoke': False,
        'pets_ok': False,
    },
]


class Command(BaseCommand):
    help = 'Seed PDX shelter and resource data'

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Delete all existing shelters before seeding')

    def handle(self, *args, **options):
        if options['clear']:
            count = Shelter.objects.count()
            Shelter.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Deleted {count} existing shelters.'))

        created = updated = 0
        for data in SHELTERS:
            name = data.pop('name')
            obj, is_new = Shelter.objects.update_or_create(
                name=name,
                defaults={**data, 'active': True},
            )
            if is_new:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} created, {updated} updated. Total: {Shelter.objects.count()} shelters.'
        ))
