"""
Django settings for communityplaylist project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from decouple import config, Csv
from pathlib import Path
CSRF_TRUSTED_ORIGINS = ['https://communityplaylist.com', 'https://www.communityplaylist.com']
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h+uj_=cyo*v!34-=wvv8_xrdk0a-pjpselopb8)aeb-jx+66=c'
SECRET_KEY = 'django-insecure-h+uj_=cyo*v!34-=wvv8_xrdk0a-pjpselopb8)aeb-jx+66=c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['communityplaylist.com', 'www.communityplaylist.com', '66.175.239.235']

# Application definition

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['communityplaylist.com', 'www.communityplaylist.com', '66.175.239.235']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events',
    'board',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'communityplaylist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'events.context_processors.admin_pending',
            ],
        },
    },
]

WSGI_APPLICATION = 'communityplaylist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Optional: Eventbrite API key for import_venue_feeds Eventbrite source type
# Get one free at https://www.eventbrite.com/platform/api
EVENTBRITE_API_KEY = config('EVENTBRITE_API_KEY', default='')

# Optional: Eventbrite API key for broad PDX event search
# Get one free at https://www.eventbrite.com/platform/api
EVENTBRITE_API_KEY = config('EVENTBRITE_API_KEY', default='')

# MusicBrainz — no key needed, free & open. Contact email for User-Agent header.
# https://musicbrainz.org/doc/MusicBrainz_API — 1 req/sec rate limit
MUSICBRAINZ_CONTACT = config('MUSICBRAINZ_CONTACT', default='hello@communityplaylist.com')

# Email — Plesk local SMTP with SASL auth
# Uses communityplaylist/email_backend.py to skip self-signed cert verification
EMAIL_BACKEND   = config('EMAIL_BACKEND', default='communityplaylist.email_backend.LocalSMTPBackend')
EMAIL_HOST      = config('EMAIL_HOST', default='localhost')
EMAIL_PORT      = config('EMAIL_PORT', default=25, cast=int)
EMAIL_USE_TLS   = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL', default='Community Playlist <noreply@communityplaylist.com>')
EMAIL_TIMEOUT = 30
SITE_URL = config('SITE_URL', default='https://communityplaylist.com')

# Admin alert emails (500 errors, etc.)
ADMINS = [('Binsky', 'andrew.jubinsky@proton.me')]
SERVER_EMAIL = 'noreply@communityplaylist.com'
