from django.urls import path
from . import views

urlpatterns = [
    # Video room (theater)
    path('video-room/', views.video_room, name='video_room'),
    path('api/video-room/messages/', views.video_room_messages, name='video_room_messages'),
    # Standalone player
    path('player/', views.player_page, name='player_page'),
    path('player/manifest.json', views.player_manifest, name='player_manifest'),

    # Music player API
    path('api/genres/filter/', views.api_genre_filter, name='api_genre_filter'),
    path('api/tracks/', views.playlist_tracks_json, name='playlist_tracks_json'),
    path('api/saved-tracks/', views.saved_tracks_json, name='saved_tracks_json'),
    path('api/videos/', views.api_video_queue, name='api_video_queue'),
    path('api/parse-lineup/', views.api_parse_lineup, name='api_parse_lineup'),
    path('api/artist-lookup/', views.api_artist_lookup, name='api_artist_lookup'),
    path('api/search/', views.api_global_search, name='api_global_search'),
    path('api/toggle-comments/', views.toggle_comments_api, name='toggle_comments_api'),
    path('api/route/', views.api_route_proxy, name='api_route_proxy'),
    path('api/events/<slug:slug>/', views.api_event_detail, name='api_event_detail'),
    path('api/shelters/', views.api_shelters, name='api_shelters'),
    path('api/lastfm/', views.api_lastfm_proxy, name='api_lastfm_proxy'),
    path('api/discogs/', views.api_discogs_proxy, name='api_discogs_proxy'),
    path('api/youtube-channel/', views.api_youtube_channel_proxy, name='api_youtube_channel_proxy'),
    path('api/youtube-search/', views.api_youtube_search_proxy, name='api_youtube_search_proxy'),
    path('api/youtube-playlist/', views.api_youtube_playlist_proxy, name='api_youtube_playlist_proxy'),
    path('save-track/', views.toggle_save_track, name='toggle_save_track'),
    path('drive-sync/', views.drive_sync, name='drive_sync'),
    path('tracks/<int:pk>/delete/', views.delete_track, name='delete_track'),
    # Promoters / Crews
    path('promoters/', views.promoter_list, name='promoter_list'),
    path('promoters/register/', views.promoter_register, name='promoter_register'),
    path('promoters/<slug:slug>/', views.promoter_detail, name='promoter_detail'),
    path('promoters/<slug:slug>/edit/', views.promoter_edit, name='promoter_edit'),
    path('promoters/<slug:slug>/sync-shop/', views.promoter_sync_shop, name='promoter_sync_shop'),
    path('promoters/<slug:slug>/reserve/<int:listing_pk>/', views.promoter_reserve, name='promoter_reserve'),
    path('promoters/<slug:slug>/reservations/', views.promoter_reservations, name='promoter_reservations'),
    path('promoters/<slug:slug>/submit-demo/', views.submit_demo, name='submit_demo'),
    path('demos/<int:pk>/delete/', views.delete_track_share, name='delete_track_share'),
    path('', views.event_list, name='event_list'),
    path('submit/', views.event_submit, name='event_submit'),
    path('archive/', views.event_archive, name='event_archive'),
    path('genres/', views.genre_autocomplete, name='genre_autocomplete'),
    path('artists/', views.artist_autocomplete, name='artist_autocomplete'),
    path('artists/add/', views.artist_add, name='artist_add'),
    path('artists/register/', views.artist_register, name='artist_register'),
    path('artists/<int:pk>/', views.artist_by_pk, name='artist_by_pk'),       # legacy redirect
    path('artists/<slug:slug>/', views.artist_profile, name='artist_profile'),
    path('artists/<slug:slug>/edit/', views.artist_edit, name='artist_edit'),
    path('events/<slug:slug>/', views.event_detail, name='event_detail'),
    path('events/<slug:slug>/lineup/', views.event_lineup_edit, name='event_lineup_edit'),
    path('events/<slug:slug>/lineup/create/', views.event_lineup_create, name='event_lineup_create'),
    path('events/<slug:slug>/claim/', views.claim_event, name='claim_event'),
    path('events/<slug:slug>/flyer/', views.event_flyer, name='event_flyer'),
    path('flyer/bg/upload/',           views.flyer_bg_upload,  name='flyer_bg_upload'),
    path('flyer/bg/<int:pk>/delete/',  views.flyer_bg_delete,  name='flyer_bg_delete'),
    path('flyer/bg/drive/',            views.flyer_bg_drive,   name='flyer_bg_drive'),
    path('events/<slug:slug>/edit/', views.event_edit, name='event_edit'),
    # Venues
    path('venues/', views.venue_list, name='venue_list'),
    path('venues/register/', views.venue_register, name='venue_register'),
    path('venues/<slug:slug>/', views.venue_detail, name='venue_detail'),
    path('venues/<slug:slug>/feed.ics', views.venue_feed, name='venue_feed'),
    path('venues/<slug:slug>/edit/', views.venue_edit, name='venue_edit'),
    # Neighborhoods
    path('neighborhoods/', views.neighborhood_list, name='neighborhood_list'),
    path('neighborhoods/<slug:slug>/', views.neighborhood_detail, name='neighborhood_detail'),
    # Calendar
    path('feed/events.ics',  views.calendar_feed, name='calendar_feed'),
    path('feed/events.rss',  views.events_rss,    name='events_rss'),
    path('shop/',            views.shop,           name='shop'),
    path('subscribe/', views.calendar_subscribe, name='calendar_subscribe'),
    path('features/', views.features_page, name='features'),
    path('credits/', views.credits_page, name='credits'),
    path('api/save-playlist/', views.save_profile_playlist, name='save_profile_playlist'),
    # Auth
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('onboarding/', views.onboarding_view, name='onboarding'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # User profiles
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('resend-verification/', views.resend_verification, name='resend_verification'),
    path('profile/settings/', views.profile_settings, name='profile_settings'),
    path('u/@<str:handle>/', views.public_profile, name='public_profile'),
    path('u/@<str:handle>/feed/', views.profile_feed, name='profile_feed'),
    path('follow/', views.toggle_follow, name='toggle_follow'),
    path('suggest-edit/', views.suggest_edit, name='suggest_edit'),
    path('privacy/', views.privacy_page, name='privacy'),
    path('report/', views.report_page, name='report'),
    path('spaces/<slug:slug>/', views.community_space_profile, name='community_space_profile'),
    path('spaces/<slug:slug>/edit/', views.community_space_edit, name='community_space_edit'),
    # Ko-fi webhook — configure this URL at ko-fi.com/manage/webhooks
    path('webhooks/kofi/', views.kofi_webhook_view, name='kofi_webhook'),
]
