# Generated by Django 6.0.3 on 2026-04-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('events', '0021_view_counts_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='events.neighborhood'),
        ),
    ]
