# Generated by Django 6.0.3 on 2026-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_socialqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('aid', 'Aid & Mutual Aid'), ('announce', 'Announcement'), ('question', 'Question'), ('offer', 'Free & Trade')], default='general', max_length=20),
        ),
    ]
